// Mocks generated by Mockito 5.4.6 from annotations
// in barbearia_app/test/features/caixa/caixa_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:barbearia_app/data/models/caixa.dart' as _i2;
import 'package:barbearia_app/data/repositories/caixa_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCaixa_0 extends _i1.SmartFake implements _i2.Caixa {
  _FakeCaixa_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CaixaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaixaRepository extends _i1.Mock implements _i3.CaixaRepository {
  MockCaixaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Caixa> consultarDia(DateTime? dia) =>
      (super.noSuchMethod(
            Invocation.method(#consultarDia, [dia]),
            returnValue: _i4.Future<_i2.Caixa>.value(
              _FakeCaixa_0(this, Invocation.method(#consultarDia, [dia])),
            ),
          )
          as _i4.Future<_i2.Caixa>);

  @override
  _i4.Future<_i2.Caixa> consultarMes(DateTime? mesAno) =>
      (super.noSuchMethod(
            Invocation.method(#consultarMes, [mesAno]),
            returnValue: _i4.Future<_i2.Caixa>.value(
              _FakeCaixa_0(this, Invocation.method(#consultarMes, [mesAno])),
            ),
          )
          as _i4.Future<_i2.Caixa>);
}
