// Mocks generated by Mockito 5.4.6 from annotations
// in barbearia_app/test/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:barbearia_app/data/models/agendamento.dart' as _i9;
import 'package:barbearia_app/data/models/caixa.dart' as _i2;
import 'package:barbearia_app/data/models/enums.dart' as _i10;
import 'package:barbearia_app/data/models/excecao_horario.dart' as _i5;
import 'package:barbearia_app/data/models/horario_funcionamento.dart' as _i4;
import 'package:barbearia_app/data/models/servico.dart' as _i3;
import 'package:barbearia_app/data/repositories/agendamento_repository.dart'
    as _i8;
import 'package:barbearia_app/data/repositories/auth_repository.dart' as _i6;
import 'package:barbearia_app/data/repositories/caixa_repository.dart' as _i11;
import 'package:barbearia_app/data/repositories/horario_repository.dart'
    as _i13;
import 'package:barbearia_app/data/repositories/servico_repository.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCaixa_0 extends _i1.SmartFake implements _i2.Caixa {
  _FakeCaixa_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServico_1 extends _i1.SmartFake implements _i3.Servico {
  _FakeServico_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHorarioFuncionamento_2 extends _i1.SmartFake
    implements _i4.HorarioFuncionamento {
  _FakeHorarioFuncionamento_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExcecaoHorario_3 extends _i1.SmartFake
    implements _i5.ExcecaoHorario {
  _FakeExcecaoHorario_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> login(String? email, String? senha) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, senha]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> temSessao() =>
      (super.noSuchMethod(
            Invocation.method(#temSessao, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [AgendamentoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepository extends _i1.Mock
    implements _i8.AgendamentoRepository {
  MockAgendamentoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i9.Agendamento>> buscarAgendaDoDia(DateTime? dia) =>
      (super.noSuchMethod(
            Invocation.method(#buscarAgendaDoDia, [dia]),
            returnValue: _i7.Future<List<_i9.Agendamento>>.value(
              <_i9.Agendamento>[],
            ),
          )
          as _i7.Future<List<_i9.Agendamento>>);

  @override
  _i7.Future<void> finalizar(int? id, _i10.FormaPagamento? forma) =>
      (super.noSuchMethod(
            Invocation.method(#finalizar, [id, forma]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cancelar(int? id, _i10.StatusAgendamento? status) =>
      (super.noSuchMethod(
            Invocation.method(#cancelar, [id, status]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [CaixaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaixaRepository extends _i1.Mock implements _i11.CaixaRepository {
  MockCaixaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Caixa> consultarDia(DateTime? dia) =>
      (super.noSuchMethod(
            Invocation.method(#consultarDia, [dia]),
            returnValue: _i7.Future<_i2.Caixa>.value(
              _FakeCaixa_0(this, Invocation.method(#consultarDia, [dia])),
            ),
          )
          as _i7.Future<_i2.Caixa>);

  @override
  _i7.Future<_i2.Caixa> consultarMes(DateTime? mesAno) =>
      (super.noSuchMethod(
            Invocation.method(#consultarMes, [mesAno]),
            returnValue: _i7.Future<_i2.Caixa>.value(
              _FakeCaixa_0(this, Invocation.method(#consultarMes, [mesAno])),
            ),
          )
          as _i7.Future<_i2.Caixa>);
}

/// A class which mocks [ServicoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicoRepository extends _i1.Mock implements _i12.ServicoRepository {
  MockServicoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.Servico>> listar() =>
      (super.noSuchMethod(
            Invocation.method(#listar, []),
            returnValue: _i7.Future<List<_i3.Servico>>.value(<_i3.Servico>[]),
          )
          as _i7.Future<List<_i3.Servico>>);

  @override
  _i7.Future<_i3.Servico> criar(
    String? nome,
    double? preco,
    int? duracaoMinutos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criar, [nome, preco, duracaoMinutos]),
            returnValue: _i7.Future<_i3.Servico>.value(
              _FakeServico_1(
                this,
                Invocation.method(#criar, [nome, preco, duracaoMinutos]),
              ),
            ),
          )
          as _i7.Future<_i3.Servico>);

  @override
  _i7.Future<_i3.Servico> atualizar(
    int? id,
    String? nome,
    double? preco,
    int? duracaoMinutos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizar, [id, nome, preco, duracaoMinutos]),
            returnValue: _i7.Future<_i3.Servico>.value(
              _FakeServico_1(
                this,
                Invocation.method(#atualizar, [
                  id,
                  nome,
                  preco,
                  duracaoMinutos,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.Servico>);

  @override
  _i7.Future<void> excluir(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluir, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [HorarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorarioRepository extends _i1.Mock implements _i13.HorarioRepository {
  MockHorarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.HorarioFuncionamento>> listarHorarios() =>
      (super.noSuchMethod(
            Invocation.method(#listarHorarios, []),
            returnValue: _i7.Future<List<_i4.HorarioFuncionamento>>.value(
              <_i4.HorarioFuncionamento>[],
            ),
          )
          as _i7.Future<List<_i4.HorarioFuncionamento>>);

  @override
  _i7.Future<_i4.HorarioFuncionamento> criarHorario(
    int? diaSemana,
    String? horaInicio,
    String? horaFim,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criarHorario, [diaSemana, horaInicio, horaFim]),
            returnValue: _i7.Future<_i4.HorarioFuncionamento>.value(
              _FakeHorarioFuncionamento_2(
                this,
                Invocation.method(#criarHorario, [
                  diaSemana,
                  horaInicio,
                  horaFim,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.HorarioFuncionamento>);

  @override
  _i7.Future<_i4.HorarioFuncionamento> atualizarHorario(
    _i4.HorarioFuncionamento? horario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarHorario, [horario]),
            returnValue: _i7.Future<_i4.HorarioFuncionamento>.value(
              _FakeHorarioFuncionamento_2(
                this,
                Invocation.method(#atualizarHorario, [horario]),
              ),
            ),
          )
          as _i7.Future<_i4.HorarioFuncionamento>);

  @override
  _i7.Future<void> excluirHorario(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluirHorario, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.ExcecaoHorario>> listarExcecoes() =>
      (super.noSuchMethod(
            Invocation.method(#listarExcecoes, []),
            returnValue: _i7.Future<List<_i5.ExcecaoHorario>>.value(
              <_i5.ExcecaoHorario>[],
            ),
          )
          as _i7.Future<List<_i5.ExcecaoHorario>>);

  @override
  _i7.Future<_i5.ExcecaoHorario> criarExcecao(
    DateTime? data,
    bool? disponivel,
    String? horaInicio,
    String? horaFim,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criarExcecao, [
              data,
              disponivel,
              horaInicio,
              horaFim,
            ]),
            returnValue: _i7.Future<_i5.ExcecaoHorario>.value(
              _FakeExcecaoHorario_3(
                this,
                Invocation.method(#criarExcecao, [
                  data,
                  disponivel,
                  horaInicio,
                  horaFim,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.ExcecaoHorario>);

  @override
  _i7.Future<void> excluirExcecao(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluirExcecao, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
