// Mocks generated by Mockito 5.4.6 from annotations
// in barbearia_app/test/features/agenda/agenda_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:barbearia_app/data/models/agendamento.dart' as _i4;
import 'package:barbearia_app/data/models/enums.dart' as _i5;
import 'package:barbearia_app/data/repositories/agendamento_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AgendamentoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepository extends _i1.Mock
    implements _i2.AgendamentoRepository {
  MockAgendamentoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Agendamento>> buscarAgendaDoDia(DateTime? dia) =>
      (super.noSuchMethod(
            Invocation.method(#buscarAgendaDoDia, [dia]),
            returnValue: _i3.Future<List<_i4.Agendamento>>.value(
              <_i4.Agendamento>[],
            ),
          )
          as _i3.Future<List<_i4.Agendamento>>);

  @override
  _i3.Future<void> finalizar(int? id, _i5.FormaPagamento? forma) =>
      (super.noSuchMethod(
            Invocation.method(#finalizar, [id, forma]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelar(int? id, _i5.StatusAgendamento? status) =>
      (super.noSuchMethod(
            Invocation.method(#cancelar, [id, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
