// Mocks generated by Mockito 5.4.6 from annotations
// in barbearia_app/test/features/configuracao/configuracao_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:barbearia_app/data/models/excecao_horario.dart' as _i3;
import 'package:barbearia_app/data/models/horario_funcionamento.dart' as _i2;
import 'package:barbearia_app/data/repositories/horario_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHorarioFuncionamento_0 extends _i1.SmartFake
    implements _i2.HorarioFuncionamento {
  _FakeHorarioFuncionamento_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExcecaoHorario_1 extends _i1.SmartFake
    implements _i3.ExcecaoHorario {
  _FakeExcecaoHorario_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HorarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorarioRepository extends _i1.Mock implements _i4.HorarioRepository {
  MockHorarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.HorarioFuncionamento>> listarHorarios() =>
      (super.noSuchMethod(
            Invocation.method(#listarHorarios, []),
            returnValue: _i5.Future<List<_i2.HorarioFuncionamento>>.value(
              <_i2.HorarioFuncionamento>[],
            ),
          )
          as _i5.Future<List<_i2.HorarioFuncionamento>>);

  @override
  _i5.Future<_i2.HorarioFuncionamento> criarHorario(
    int? diaSemana,
    String? horaInicio,
    String? horaFim,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criarHorario, [diaSemana, horaInicio, horaFim]),
            returnValue: _i5.Future<_i2.HorarioFuncionamento>.value(
              _FakeHorarioFuncionamento_0(
                this,
                Invocation.method(#criarHorario, [
                  diaSemana,
                  horaInicio,
                  horaFim,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.HorarioFuncionamento>);

  @override
  _i5.Future<_i2.HorarioFuncionamento> atualizarHorario(
    _i2.HorarioFuncionamento? horario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarHorario, [horario]),
            returnValue: _i5.Future<_i2.HorarioFuncionamento>.value(
              _FakeHorarioFuncionamento_0(
                this,
                Invocation.method(#atualizarHorario, [horario]),
              ),
            ),
          )
          as _i5.Future<_i2.HorarioFuncionamento>);

  @override
  _i5.Future<void> excluirHorario(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluirHorario, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ExcecaoHorario>> listarExcecoes() =>
      (super.noSuchMethod(
            Invocation.method(#listarExcecoes, []),
            returnValue: _i5.Future<List<_i3.ExcecaoHorario>>.value(
              <_i3.ExcecaoHorario>[],
            ),
          )
          as _i5.Future<List<_i3.ExcecaoHorario>>);

  @override
  _i5.Future<_i3.ExcecaoHorario> criarExcecao(
    DateTime? data,
    bool? disponivel,
    String? horaInicio,
    String? horaFim,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criarExcecao, [
              data,
              disponivel,
              horaInicio,
              horaFim,
            ]),
            returnValue: _i5.Future<_i3.ExcecaoHorario>.value(
              _FakeExcecaoHorario_1(
                this,
                Invocation.method(#criarExcecao, [
                  data,
                  disponivel,
                  horaInicio,
                  horaFim,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.ExcecaoHorario>);

  @override
  _i5.Future<void> excluirExcecao(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluirExcecao, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
