// Mocks generated by Mockito 5.4.6 from annotations
// in barbearia_app/test/features/servicos/servicos_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:barbearia_app/data/models/servico.dart' as _i2;
import 'package:barbearia_app/data/repositories/servico_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeServico_0 extends _i1.SmartFake implements _i2.Servico {
  _FakeServico_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServicoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicoRepository extends _i1.Mock implements _i3.ServicoRepository {
  MockServicoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Servico>> listar() =>
      (super.noSuchMethod(
            Invocation.method(#listar, []),
            returnValue: _i4.Future<List<_i2.Servico>>.value(<_i2.Servico>[]),
          )
          as _i4.Future<List<_i2.Servico>>);

  @override
  _i4.Future<_i2.Servico> criar(
    String? nome,
    double? preco,
    int? duracaoMinutos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criar, [nome, preco, duracaoMinutos]),
            returnValue: _i4.Future<_i2.Servico>.value(
              _FakeServico_0(
                this,
                Invocation.method(#criar, [nome, preco, duracaoMinutos]),
              ),
            ),
          )
          as _i4.Future<_i2.Servico>);

  @override
  _i4.Future<_i2.Servico> atualizar(
    int? id,
    String? nome,
    double? preco,
    int? duracaoMinutos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizar, [id, nome, preco, duracaoMinutos]),
            returnValue: _i4.Future<_i2.Servico>.value(
              _FakeServico_0(
                this,
                Invocation.method(#atualizar, [
                  id,
                  nome,
                  preco,
                  duracaoMinutos,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Servico>);

  @override
  _i4.Future<void> excluir(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#excluir, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
